version: '3'
services:
  wp:
    depends_on:
     - wp_mysql
    image: wordpress:latest
    ports:
     - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wp_mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
     - "./illarion:/var/www/html/wp-content/themes/illarion"

  wp_mysql:
    image: mysql:5.7
    volumes:
     - wp_mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  wp_mysql_data: